[build]
  command = "node scripts/migrate.js && gatsby build"
  functions = "netlify/functions"
  publish = "public"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[dev]
  targetPort = 8000
  port = 8888
